import Head from "next/head";
import NextTable from "./uiComponents/nextTable";
import NextCards from "./uiComponents/nextCards";
import get_etf_list from "../../repo/etfList";

const validMap: { [key: string]: any } = { tw: [], asia: [], global: [], us: [] };

type DataItem = {
  stock_no: string;
  price: string;
  y_price: string;
  volume: string;
  type: 'tw' | 'asia' | 'global' | 'us';
  name: string;
  estimate_value: string;
  y_estimate_value: string;
  value_diff: string;
  update_time: string;
};
async function fetchData() {
  const data: DataItem[] | null = await get_etf_list();
console.log({data})
  if (data === null) {
    return [];
  }
 data.forEach((item: DataItem) => validMap[item.type].push(item));


}
export default async function Page() {
  await fetchData();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center h-screen bg-black overflow-y-auto">
        <div className="flex flex-col w-4/6">
          <NextCards />
          <NextTable latestData={validMap} />
        </div>
      </main>
    </>
  );
}
